on:
  workflow_call: # Added this line to make it reusable
    inputs:
      build_platform:
        required: true
        type: string
      build_platform_name:
        required: true
        type: string
      build_mode:
        required: true
        type: string
      bundle_binaries:
        required: true
        type: boolean

jobs:

  # Windows
  build-transpiler-on-windows-latest:
    name: Windows ${{inputs.build_platform_name}}
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11 (or later)
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1.13.0

    - name: Make the "transpiler/build" directory
      run: mkdir ${{github.workspace}}/transpiler/build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=${{inputs.build_mode}} -A ${{inputs.build_platform}}
      working-directory: transpiler/build

    - name: Build
      run: cmake --build . --config ${{inputs.build_mode}}
      working-directory: transpiler/build

    - name: Run Tests
      run: ctest -VV -C ${{inputs.build_mode}}
      working-directory: transpiler/build

    - name: Extract version (optional)
      if: inputs.bundle_binaries
      run: |
        $version = Get-Content "${{github.workspace}}/transpiler/manifest.ini" | Where-Object { $_ -match 'VERSION=' } | ForEach-Object { ($_ -split '=')[1].Trim('"') }
        if ($version) {
          echo "VERSION=$version" >> $env:GITHUB_ENV
        } else {
          Write-Error "VERSION not found in manifest.ini"
          exit 1
        }

    - name: Upload Binaries Artifact (optional)
      if: inputs.bundle_binaries
      uses: actions/upload-artifact@v4
      with:
        name: PolarFrankie-${{inputs.build_mode}}-v${{env.VERSION}}-Windows-${{inputs.build_platform_name}}
        path: ${{github.workspace}}/transpiler/dist/${{inputs.build_mode}}/${{inputs.build_platform_name}}/
