on:
  workflow_call: # Added this line to make it reusable
    inputs:
      build_mode:
        required: true
        type: string
      bundle_binaries:
        required: true
        type: boolean

jobs:

  # Windows
  build-transpiler-on-windows-latest-x86-64:
    name: Windows
    uses: ./.github/workflows/_transpiler_windows_build.yml
    with:
      build_platform: x64
      build_platform_name: x86_64
      build_mode: Debug
      bundle_binaries: false

  # Unix-like (Windows, macOS)
  build-transpiler-on-unix-like-latest-x86-64:
    name: Unix-like
    uses: ./.github/workflows/_transpiler_unix_like_build.yml
    with:
      build_platform: x64
      build_platform_name: x86_64
      build_mode: Debug
      bundle_binaries: false
