name: Build the transpiler
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Windows
  build-windows-latest:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # or 'adopt' before temurin.

    - name: Navigate to "transpiler/build"
      run: mkdir ${{github.workspace}}/transpiler/build && cd ${{github.workspace}}/transpiler/build

    - name: Configure CMake
      run: cd ${{github.workspace}}/transpiler/build && cmake ${{github.workspace}}/transpiler -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cd ${{github.workspace}}/transpiler/build && cmake --build ${{github.workspace}}/transpiler/build --config Release

    #- name: Run Tests
    #  run: ctest --test-dir ${{github.workspace}}/build --config Release

  # Linux
  build-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Navigate to "transpiler/build"
      run: mkdir ${{github.workspace}}/transpiler/build && cd ${{github.workspace}}/transpiler/build

    - name: Configure CMake
      run: cmake ${{github.workspace}}/transpiler -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/transpiler/build --config Release

    #- name: Run Tests
    #  run: ctest --test-dir ${{github.workspace}}/build --config Release
