name: Build the transpiler
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # Windows
  build-windows-latest:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1

    - name: Navigate to "build"
      run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build . --config Release

    #- name: Run Tests
    #  run: ctest --test-dir ${{github.workspace}}/build --config Release

  # Linux
  build-ubuntu-latest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Navigate to "build"
      run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build

    - name: Configure CMake
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build . --config Release

    #- name: Run Tests
    #  run: ctest --test-dir ${{github.workspace}}/build --config Release
