name: VSCode Extension
on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"
  workflow_call: # Added this line to make it reusable
    # Add inputs here if needed. Example:
    # inputs:
    #   some_input:
    #     required: true
    #     type: boolean

jobs:

  # Windows
  build-vscode-extension-on-windows-latest:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install NodeJS dependencies
      run: npm i
      working-directory: supplements/VSCode-Extension

    - name: Package the VSCode Extension
      run: npm run win-package
      working-directory: supplements/VSCode-Extension

#  # Linux
#  build-vscode-extension-on-ubuntu-latest:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Install NodeJS dependencies
#      run: npm i
#      working-directory: supplements/VSCode-Extension
#
#    - name: Package the VSCode Extension
#      run: npm run lix-package
#      working-directory: supplements/VSCode-Extension

#  # macOS
#  build-vscode-extension-on-macos-latest:
#    runs-on: macos-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Install NodeJS dependencies
#      run: npm i
#      working-directory: supplements/VSCode-Extension
#
#    - name: Package the VSCode Extension
#      run: npm run lix-package
#      working-directory: supplements/VSCode-Extension
