name: VSCode Extension
on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main"
  workflow_call: # Added this line to make it reusable
    # Add inputs here if needed. Example:
    inputs:
      upload_artifact:
        required: false
        type: boolean
        default: false

jobs:

  # Windows
  build-vscode-extension-on-windows-latest:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install NodeJS dependencies
      run: npm i
      working-directory: ${{github.workspace}}/supplements/VSCode-Extension

    - name: Package the VSCode Extension
      run: npm run win-package
      working-directory: ${{github.workspace}}/supplements/VSCode-Extension

    - name: Get VSCode Extension version
      id: get-file
      run: |
        $FilePath = Get-ChildItem -Path "./" -Filter "*.vsix" | Select-Object -First 1 | Select-Object -ExpandProperty FullName
        if ($FilePath) {
          $FileName = Split-Path -Path $FilePath -Leaf
          $VersionWithExt = $FileName.Replace("polarfrankie-", "")
          $NewFileName = "PolarFrankie-VSCode-v$VersionWithExt";
          mv $FileName $NewFileName # Rename the file
          echo "VSCODE_EXT_FILE_NAME=$NewFileName" >> $env:GITHUB_ENV
        } else {
          Write-Error "No .vsix files found in ${{github.workspace}}/supplements/VSCode-Extension/"
        }
      working-directory: ${{github.workspace}}/supplements/VSCode-Extension

    - name: Upload Binaries Artifact (optional)
      if: inputs.upload_artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.VSCODE_EXT_FILE_NAME}}
        path: ${{github.workspace}}/supplements/VSCode-Extension/${{env.VSCODE_EXT_FILE_NAME}}

#  # Linux
#  build-vscode-extension-on-ubuntu-latest:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Install NodeJS dependencies
#      run: npm i
#      working-directory: supplements/VSCode-Extension
#
#    - name: Package the VSCode Extension
#      run: npm run lix-package
#      working-directory: supplements/VSCode-Extension

#  # macOS
#  build-vscode-extension-on-macos-latest:
#    runs-on: macos-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v3
#
#    - name: Install NodeJS dependencies
#      run: npm i
#      working-directory: supplements/VSCode-Extension
#
#    - name: Package the VSCode Extension
#      run: npm run lix-package
#      working-directory: supplements/VSCode-Extension
